name: translate_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  translator: ^0.1.2
  provider: 2.0.1+1
  flutter_spinkit: ^3.1.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
  assets:
    - assets/translate.png

  uses-material-design: true